### ISSUE TITLE
Bug: Transport rings no longer drop

### ISSUE THREAD

**Issue by MR-Spagetty** [Tau-ri-Dev/JSGMod-1.12.2#190]
**Describe the bug**
when you break transport rings in survival mode with the appropriate pickaxe it no longer drops the item

**To Reproduce**
1. place transport rings
2. break transport rings with diamond pickaxe
_3. cry as you just lost a set of your transport rings_

**Expected behavior**
the item should be dropped when they are broken with a diamond pickaxe

**Mod version**
jsg-1.12.2-4.10.1.1-client.jar

**Comment by CryptAlchemy** [comment]
Can confirm.

**Comment by CryptAlchemy** [comment]
Plus, caused this crash when breaking rings:

```
java.lang.NullPointerException: Ticking player
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.hasPlatformSpace(TransportRingsAbstractTile.java:238)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.tryBuildPlatformPattern(TransportRingsAbstractTile.java:288)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.updatePlatformStatus(TransportRingsAbstractTile.java:223)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.onBreak(TransportRingsAbstractTile.java:429)
	at tauri.dev.jsg.block.transportrings.TransportRingsAbstractBlock.func_180663_b(TransportRingsAbstractBlock.java:72)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:567)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1179)
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:324)
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:109)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:316)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by MineDragonCZ** [comment]
Probably fixed in dev
