### ISSUE TITLE
Bug: Null pointer around ZPM energy storage

### ISSUE THREAD

**Issue by FamousL** [Tau-ri-Dev/JSGMod-1.12.2#220]
**Describe the bug**
Server crash with following error:

java.lang.NullPointerException: Ticking block entity
        at tauri.dev.jsg.stargate.power.StargateClassicEnergyStorage.getEnergyStored(StargateClassicEnergyStorage.java:33)
        at tauri.dev.jsg.tileentity.energy.ZPMHubTile.func_73660_a(ZPMHubTile.java:179)
        at net.minecraft.world.World.func_72939_s(World.java:1838)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:750)

**To Reproduce**
Server with both Extra utils2 and jsg mod installed
Create Extra utils quantum quarry
Power quarry with Tauri zpm socket, zpm socket was directly next to the bottom actuator, inserted a zpm
pull zpm

**Expected behavior**
no crash

**Mod version**
jsg-1.12.2-4.11.0.3-client.jar

**Additional context**
Quarry had been running for a while and depleted the zpm that was attached, zpm was already sub 10% remaining entropy when installed.

**Comment by MineDragonCZ** [comment]
Is it still happening with 4.11.0.4 ?

**Comment by FamousL** [comment]
Testing

**Comment by FamousL** [comment]
Yes still happening, new stacktrace:
java.lang.NullPointerException: Ticking block entity
        at java.util.Objects.requireNonNull(Objects.java:203)
        at tauri.dev.jsg.tileentity.energy.ZPMHubTile.getState(ZPMHubTile.java:307)
        at tauri.dev.jsg.tileentity.energy.ZPMHubTile$1.onContentsChanged(ZPMHubTile.java:93)
        at net.minecraftforge.items.ItemStackHandler.insertItem(ItemStackHandler.java:113)
        at com.rwtema.extrautils2.itemhandler.InventoryHelper.insert(InventoryHelper.java:127)
        at com.rwtema.extrautils2.itemhandler.StackDump.attemptDump(StackDump.java:72)
        at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:365)
        at net.minecraft.world.World.func_72939_s(World.java:1838)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:750)


Additional info: Looks like the quarry sees the zpm socket as a valid location to deposit non-zpm items?

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at java.util.Objects.requireNonNull(Objects.java:203)
        at tauri.dev.jsg.tileentity.energy.ZPMHubTile.getState(ZPMHubTile.java:307)
        at tauri.dev.jsg.tileentity.energy.ZPMHubTile$1.onContentsChanged(ZPMHubTile.java:93)
        at net.minecraftforge.items.ItemStackHandler.insertItem(ItemStackHandler.java:113)
        at com.rwtema.extrautils2.itemhandler.InventoryHelper.insert(InventoryHelper.java:127)
        at com.rwtema.extrautils2.itemhandler.StackDump.attemptDump(StackDump.java:72)
        at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:365)

-- Block entity being ticked --
Details:
        Name: xu2:tilequarry // com.rwtema.extrautils2.quarry.TileQuarry
        Block type: ID #300 (tile.extrautils2:quarry // com.rwtema.extrautils2.quarry.BlockQuarry // extrautils2:quarry)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-1957,48,37), Chunk: (at 11,3,5 in -123,2; contains blocks -1968,0,32 to -1953,255,47), Region: (-4,0; contains chunks -128,0 to -97,31, blocks -2048,0,0 to -
1537,255,511)
        Actual block type: ID #300 (tile.extrautils2:quarry // com.rwtema.extrautils2.quarry.BlockQuarry // extrautils2:quarry)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1838)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

**Comment by MineDragonCZ** [comment]
Yea, probably incompatibility with ExtraUtils2. I will try to fix that, but if i can't, I will mark that mod as incompatible :)

**Comment by MineDragonCZ** [comment]
Can i get your discord, please?

**Comment by FamousL** [comment]
Sent via email to the email attached to your profile.

**Comment by MineDragonCZ** [comment]
> Sent via email to the email attached to your profile.

Sorry, but i noticed that i had wrong email on my profile. New is: vojtech.sin@justsgmod.eu

**Comment by MineDragonCZ** [comment]
Should be fixed
