### ISSUE TITLE
Bug: Pixelmon/Stargate interaction crash

### ISSUE THREAD

**Issue by FamousL** [Tau-ri-Dev/JSGMod-1.12.2#233]
**Describe the bug**
Pixelmon pokemon attempted to gate travel to the End dimension using a stargate I had dialed. 

**To Reproduce**
Pixelmon/Jsg must be present
Pixemon must attempt to walk through the gate when dialed 

**Expected behavior**
Pixelmon ends up on the far side, like arrows and the like

**Mod version**
jsg-1.12.2-4.11.0.5-client.jar

**Additional context**
// You're mean.

Time: 3/3/23 2:24 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at tauri.dev.jsg.stargate.teleportation.TeleportHelper.setMotion(TeleportHelper.java:210)
        at tauri.dev.jsg.stargate.teleportation.TeleportHelper.teleportEntity(TeleportHelper.java:146)
        at tauri.dev.jsg.stargate.teleportation.TeleportPacket.teleport(TeleportPacket.java:49)
        at tauri.dev.jsg.stargate.teleportation.TeleportPacket.teleport(TeleportPacket.java:44)
        at tauri.dev.jsg.stargate.teleportation.EventHorizon.teleportEntity(EventHorizon.java:220)
        at tauri.dev.jsg.stargate.teleportation.EventHorizon.scheduleTeleportation(EventHorizon.java:112)
        at tauri.dev.jsg.tileentity.stargate.StargateAbstractBaseTile.func_73660_a(StargateAbstractBaseTile.java:931)
        at tauri.dev.jsg.tileentity.stargate.StargateClassicBaseTile.func_73660_a(StargateClassicBaseTile.java:922)
        at tauri.dev.jsg.tileentity.stargate.StargateMilkyWayBaseTile.func_73660_a(StargateMilkyWayBaseTile.java:401)
        at net.minecraft.world.World.func_72939_s(World.java:1838)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:750)

**Comment by MineDragonCZ** [comment]
Should be fixed
