### ISSUE TITLE
Crash Bug: Naturally generated Transport Rings

### ISSUE THREAD

**Issue by Sarous** [Tau-ri-Dev/JSGMod-1.12.2#237]
**Describe the bug**
Game crash, precise reason unknown.

**To Reproduce**
Not easily reproducible.

**Expected behavior**
Unknown, as the cause is unknown.

**Mod version**
jsg-1.12.2-4.11.0.5-client

**Additional context**
Walking along a new save, generating new terrain as I was traveling to unexplored area.

<details>
<summary>Crash Log</summary
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  FloatingItems (FloatingItems-1.12.2-0.1.0.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-0.2.11.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-13.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/10/23 9:19 AM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.tileentity.TileEntityStructure cannot be cast to tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.setRingsParams(TransportRingsAbstractTile.java:1008)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.setRingsParams(TransportRingsAbstractTile.java:987)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.generateAddress(TransportRingsAbstractTile.java:466)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.onLoad(TransportRingsAbstractTile.java:438)
	at net.minecraft.world.World.func_175700_a(World.java:1924)
	at net.minecraft.world.World.func_147448_a(World.java:1951)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2187978592 bytes (2086 MB) / 4630511616 bytes (4416 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 6
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 72 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version               | Source                                         | Signature                                |
	|:------ |:--------------------- |:--------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                   | 9.42                  | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                   | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | infinimend            | 1.0.2                 | minecraft.jar                                  | None                                     |
	| LCHIJA | randompatches         | 1.12.2-1.22.1.7       | randompatches-1.12.2-1.22.1.7.jar              | None                                     |
	| LCHIJA | 113_water_mechanics   | 1.0.4                 | 1.13WaterMechanicsBackport-1.0.5-1.12.2.jar    | None                                     |
	| LCHIJA | ic2                   | 2.8.222-ex112         | industrialcraft-2-2.8.222-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | libvulpes             | 0.4.2.-25             | LibVulpes-1.12.2-0.4.2-25-universal.jar        | None                                     |
	| LCHIJA | advancedrocketry      | 1.12.2-2.0.0-13       | AdvancedRocketry-1.12.2-2.0.0-13.jar           | None                                     |
	| LCHIJA | aether_legacy         | 1.5.3.2               | aether-1.12.2-v1.5.3.2.jar                     | None                                     |
	| LCHIJA | amidst-forge          | 1.12.2-0.6.2          | amidst-forge-1.12.2-0.6.2.jar                  | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2445            | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar  | None                                     |
	| LCHIJA | craftstudioapi        | 1.0.0                 | CraftStudio-1.0.0.93-mc1.12-alpha.jar          | None                                     |
	| LCHIJA | twilightforest        | 3.11.1021             | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
	| LCHIJA | animania              | 2.0.3.28              | animania-1.12.2-base-2.0.3.28.jar              | None                                     |
	| LCHIJA | crafttweaker          | 4.1.20                | CraftTweaker2-1.12-4.1.20.683.jar              | None                                     |
	| LCHIJA | jei                   | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCHIJA | quark                 | r1.6-179              | Quark-r1.6-179.jar                             | None                                     |
	| LCHIJA | autoreglib            | 1.3-32                | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCHIJA | gorecore              | 1.12.2-0.4.5          | avatarmod-1.6.2.jar                            | None                                     |
	| LCHIJA | avatarmod             | 1.6.2                 | avatarmod-1.6.2.jar                            | None                                     |
	| LCHIJA | bookshelf             | 2.3.590               | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bookworm              | 1.12.2-2.5.2.1        | bookworm-1.12.2-2.5.2.1.jar                    | None                                     |
	| LCHIJA | chunkpregenerator     | 2.5.0                 | Chunk+Pregenerator-V1.12-2.5.7.jar             | None                                     |
	| LCHIJA | clumps                | 3.1.2                 | Clumps-3.1.2.jar                               | None                                     |
	| LCHIJA | collective            | 3.0                   | collective-1.12.2-3.0.jar                      | None                                     |
	| LCHIJA | extendedrenderer      | v1.0                  | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | coroutil              | 1.12.1-1.2.37         | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | configmod             | v1.0                  | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | ctgui                 | 1.0.0                 | CraftTweaker2-1.12-4.1.20.683.jar              | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.3                 | CraftTweaker2-1.12-4.1.20.683.jar              | None                                     |
	| LCHIJA | creaturebeacons       | 1.12.2-1.0.1          | creaturebeacons-1.12.2-1.0.1.jar               | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | dynamictrees          | 1.12.2-0.9.29         | DynamicTrees-1.12.2-0.9.29.jar                 | None                                     |
	| LCHIJA | dynamictreesbop       | 1.12.2-1.5.1          | DynamicTreesBOP-1.12.2-1.5.1.jar               | None                                     |
	| LCHIJA | dynamictreesic2       | 1.12.2-1.2.3          | DynamicTreesIC2-1.12.2-1.2.3.jar               | None                                     |
	| LCHIJA | dynamictreesquark     | 1.12.2-1.0.6          | DynamicTreesQuark-1.12.2-1.0.6.jar             | None                                     |
	| LCHIJA | dynamictreestheaether | 1.0.14                | DynamicTreesTheAether-1.12.2-1.0.14.jar        | None                                     |
	| LCHIJA | dynamictreesttf       | 1.12.2-1.2.3          | dynamictreesTheTwilightForest-1.12.2-1.2.3.jar | None                                     |
	| LCHIJA | eplus                 | 5.0.176               | EnchantingPlus-1.12.2-5.0.176.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | energyconverters      | 1.3.7.30              | energyconverters_1.12.2-1.3.7.30.jar           | None                                     |
	| LCHIJA | erebus                | 1.0.32                | Erebus-1.0.32.jar                              | None                                     |
	| LCHIJA | exoticbirds           | 1.0                   | Exotic+Birds+1.12.2-3.2.0.jar                  | None                                     |
	| LCHIJA | golems                | 7.1.9                 | ExtraGolems-1.12-7.1.9.jar                     | None                                     |
	| LCHIJA | floatingitems         | 0.1.0                 | FloatingItems-1.12.2-0.1.0.jar                 | None                                     |
	| LCHIJA | forgelin              | 1.8.4                 | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | forgivingvoid         | 1.1.0                 | ForgivingVoid_1.12.2-1.1.0.jar                 | None                                     |
	| LCHIJA | futuremc              | 0.2.6                 | future-mc-0.2.11.jar                           | None                                     |
	| LCHIJA | geographicraft        | 0.8.7                 | GeographiCraft-1.12-0.8.9b.jar                 | None                                     |
	| LCHIJA | waila                 | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCHIJA | llibrary              | 1.7.20                | llibrary-1.7.20-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire            | 1.9.1                 | iceandfire-1.9.1-1.12.2.jar                    | None                                     |
	| LCHIJA | ichunutil             | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | infinitefluids        | 1.2.0                 | infinitefluids-1.11-1.2.0.jar                  | None                                     |
	| LCHIJA | infinitetrading       | 1.4                   | infinitetrading_1.12.2-1.4.jar                 | None                                     |
	| LCHIJA | invtotem              | 1.0                   | invtotem_1.12-1.0.jar                          | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCHIJA | jsg                   | 1.12.2-4.11.0.5       | jsg-1.12.2-4.11.0.5-client.jar                 | None                                     |
	| LCHIJA | malisiscore           | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| LCHIJA | radixcore             | 1.12.x-2.2.1          | RadixCore-1.12.x-2.2.1-universal.jar           | None                                     |
	| LCHIJA | mca                   | 1.12.2-5.3.1          | MCA-1.12.x-5.3.1-universal.jar                 | None                                     |
	| LCHIJA | noanvilcost           | 1.0.0                 | NoAnvilCost.jar                                | None                                     |
	| LCHIJA | norecipebook          | 1.2.1                 | noRecipeBook_v1.2.2formc1.12.2.jar             | None                                     |
	| LCHIJA | notenoughpets         | 2.3.4                 | NotEnoughPets-1.12.2-2.3.4.jar                 | None                                     |
	| LCHIJA | quarkoddities         | 1                     | QuarkOddities-1.12.2.jar                       | None                                     |
	| LCHIJA | randomtweaks          | 1.12.2-2.8.3.1        | randomtweaks-1.12.2-2.8.3.1.jar                | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCHIJA | sereneseasons         | 1.2.18                | SereneSeasons-1.12.2-1.2.18-universal.jar      | None                                     |
	| LCHIJA | serenetweaks          | 0.0.1                 | SereneTweaks-1.0.jar                           | None                                     |
	| LCHIJA | weather2              | 1.12.1-2.6.12         | weather2-1.12.1-2.6.12.jar                     | None                                     |
	| LCHIJA | ic2_tweaker           | 0.2.1+build.4         | ic2-tweaker-0.2.1+build.4.jar                  | None                                     |
	| LCHIJA | rtg                   | 6.1.0.0-snapshot.1    | RTG-1.12.2-6.1.0.0-snapshot.1.jar              | None                                     |
	| UD     | advancedrocketrycore  | 1                     | minecraft.jar                                  | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
FloatingItems (FloatingItems-1.12.2-0.1.0.jar)
  
RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  com.therandomlabs.randompatches.core.RPTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
FutureMC (future-mc-0.2.11.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-13.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Sarous'/137976, l='Aurora', x=939.79, y=64.00, z=1711.19]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6286
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4
</details>

Update:
Upon logging back in, instantly crashed a second time.

<details>
<summary> Second crash </summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  FloatingItems (FloatingItems-1.12.2-0.1.0.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-0.2.11.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-13.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/10/23 9:19 AM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.tileentity.TileEntityStructure cannot be cast to tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.setRingsParams(TransportRingsAbstractTile.java:1008)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.setRingsParams(TransportRingsAbstractTile.java:987)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.generateAddress(TransportRingsAbstractTile.java:466)
	at tauri.dev.jsg.tileentity.transportrings.TransportRingsAbstractTile.onLoad(TransportRingsAbstractTile.java:438)
	at net.minecraft.world.World.func_175700_a(World.java:1924)
	at net.minecraft.world.World.func_147448_a(World.java:1951)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2187978592 bytes (2086 MB) / 4630511616 bytes (4416 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 6
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 72 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version               | Source                                         | Signature                                |
	|:------ |:--------------------- |:--------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                   | 9.42                  | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                   | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | infinimend            | 1.0.2                 | minecraft.jar                                  | None                                     |
	| LCHIJA | randompatches         | 1.12.2-1.22.1.7       | randompatches-1.12.2-1.22.1.7.jar              | None                                     |
	| LCHIJA | 113_water_mechanics   | 1.0.4                 | 1.13WaterMechanicsBackport-1.0.5-1.12.2.jar    | None                                     |
	| LCHIJA | ic2                   | 2.8.222-ex112         | industrialcraft-2-2.8.222-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | libvulpes             | 0.4.2.-25             | LibVulpes-1.12.2-0.4.2-25-universal.jar        | None                                     |
	| LCHIJA | advancedrocketry      | 1.12.2-2.0.0-13       | AdvancedRocketry-1.12.2-2.0.0-13.jar           | None                                     |
	| LCHIJA | aether_legacy         | 1.5.3.2               | aether-1.12.2-v1.5.3.2.jar                     | None                                     |
	| LCHIJA | amidst-forge          | 1.12.2-0.6.2          | amidst-forge-1.12.2-0.6.2.jar                  | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2445            | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar  | None                                     |
	| LCHIJA | craftstudioapi        | 1.0.0                 | CraftStudio-1.0.0.93-mc1.12-alpha.jar          | None                                     |
	| LCHIJA | twilightforest        | 3.11.1021             | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
	| LCHIJA | animania              | 2.0.3.28              | animania-1.12.2-base-2.0.3.28.jar              | None                                     |
	| LCHIJA | crafttweaker          | 4.1.20                | CraftTweaker2-1.12-4.1.20.683.jar              | None                                     |
	| LCHIJA | jei                   | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCHIJA | quark                 | r1.6-179              | Quark-r1.6-179.jar                             | None                                     |
	| LCHIJA | autoreglib            | 1.3-32                | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCHIJA | gorecore              | 1.12.2-0.4.5          | avatarmod-1.6.2.jar                            | None                                     |
	| LCHIJA | avatarmod             | 1.6.2                 | avatarmod-1.6.2.jar                            | None                                     |
	| LCHIJA | bookshelf             | 2.3.590               | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bookworm              | 1.12.2-2.5.2.1        | bookworm-1.12.2-2.5.2.1.jar                    | None                                     |
	| LCHIJA | chunkpregenerator     | 2.5.0                 | Chunk+Pregenerator-V1.12-2.5.7.jar             | None                                     |
	| LCHIJA | clumps                | 3.1.2                 | Clumps-3.1.2.jar                               | None                                     |
	| LCHIJA | collective            | 3.0                   | collective-1.12.2-3.0.jar                      | None                                     |
	| LCHIJA | extendedrenderer      | v1.0                  | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | coroutil              | 1.12.1-1.2.37         | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | configmod             | v1.0                  | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | ctgui                 | 1.0.0                 | CraftTweaker2-1.12-4.1.20.683.jar              | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.3                 | CraftTweaker2-1.12-4.1.20.683.jar              | None                                     |
	| LCHIJA | creaturebeacons       | 1.12.2-1.0.1          | creaturebeacons-1.12.2-1.0.1.jar               | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | dynamictrees          | 1.12.2-0.9.29         | DynamicTrees-1.12.2-0.9.29.jar                 | None                                     |
	| LCHIJA | dynamictreesbop       | 1.12.2-1.5.1          | DynamicTreesBOP-1.12.2-1.5.1.jar               | None                                     |
	| LCHIJA | dynamictreesic2       | 1.12.2-1.2.3          | DynamicTreesIC2-1.12.2-1.2.3.jar               | None                                     |
	| LCHIJA | dynamictreesquark     | 1.12.2-1.0.6          | DynamicTreesQuark-1.12.2-1.0.6.jar             | None                                     |
	| LCHIJA | dynamictreestheaether | 1.0.14                | DynamicTreesTheAether-1.12.2-1.0.14.jar        | None                                     |
	| LCHIJA | dynamictreesttf       | 1.12.2-1.2.3          | dynamictreesTheTwilightForest-1.12.2-1.2.3.jar | None                                     |
	| LCHIJA | eplus                 | 5.0.176               | EnchantingPlus-1.12.2-5.0.176.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | energyconverters      | 1.3.7.30              | energyconverters_1.12.2-1.3.7.30.jar           | None                                     |
	| LCHIJA | erebus                | 1.0.32                | Erebus-1.0.32.jar                              | None                                     |
	| LCHIJA | exoticbirds           | 1.0                   | Exotic+Birds+1.12.2-3.2.0.jar                  | None                                     |
	| LCHIJA | golems                | 7.1.9                 | ExtraGolems-1.12-7.1.9.jar                     | None                                     |
	| LCHIJA | floatingitems         | 0.1.0                 | FloatingItems-1.12.2-0.1.0.jar                 | None                                     |
	| LCHIJA | forgelin              | 1.8.4                 | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | forgivingvoid         | 1.1.0                 | ForgivingVoid_1.12.2-1.1.0.jar                 | None                                     |
	| LCHIJA | futuremc              | 0.2.6                 | future-mc-0.2.11.jar                           | None                                     |
	| LCHIJA | geographicraft        | 0.8.7                 | GeographiCraft-1.12-0.8.9b.jar                 | None                                     |
	| LCHIJA | waila                 | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCHIJA | llibrary              | 1.7.20                | llibrary-1.7.20-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire            | 1.9.1                 | iceandfire-1.9.1-1.12.2.jar                    | None                                     |
	| LCHIJA | ichunutil             | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | infinitefluids        | 1.2.0                 | infinitefluids-1.11-1.2.0.jar                  | None                                     |
	| LCHIJA | infinitetrading       | 1.4                   | infinitetrading_1.12.2-1.4.jar                 | None                                     |
	| LCHIJA | invtotem              | 1.0                   | invtotem_1.12-1.0.jar                          | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCHIJA | jsg                   | 1.12.2-4.11.0.5       | jsg-1.12.2-4.11.0.5-client.jar                 | None                                     |
	| LCHIJA | malisiscore           | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| LCHIJA | radixcore             | 1.12.x-2.2.1          | RadixCore-1.12.x-2.2.1-universal.jar           | None                                     |
	| LCHIJA | mca                   | 1.12.2-5.3.1          | MCA-1.12.x-5.3.1-universal.jar                 | None                                     |
	| LCHIJA | noanvilcost           | 1.0.0                 | NoAnvilCost.jar                                | None                                     |
	| LCHIJA | norecipebook          | 1.2.1                 | noRecipeBook_v1.2.2formc1.12.2.jar             | None                                     |
	| LCHIJA | notenoughpets         | 2.3.4                 | NotEnoughPets-1.12.2-2.3.4.jar                 | None                                     |
	| LCHIJA | quarkoddities         | 1                     | QuarkOddities-1.12.2.jar                       | None                                     |
	| LCHIJA | randomtweaks          | 1.12.2-2.8.3.1        | randomtweaks-1.12.2-2.8.3.1.jar                | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCHIJA | sereneseasons         | 1.2.18                | SereneSeasons-1.12.2-1.2.18-universal.jar      | None                                     |
	| LCHIJA | serenetweaks          | 0.0.1                 | SereneTweaks-1.0.jar                           | None                                     |
	| LCHIJA | weather2              | 1.12.1-2.6.12         | weather2-1.12.1-2.6.12.jar                     | None                                     |
	| LCHIJA | ic2_tweaker           | 0.2.1+build.4         | ic2-tweaker-0.2.1+build.4.jar                  | None                                     |
	| LCHIJA | rtg                   | 6.1.0.0-snapshot.1    | RTG-1.12.2-6.1.0.0-snapshot.1.jar              | None                                     |
	| UD     | advancedrocketrycore  | 1                     | minecraft.jar                                  | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
FloatingItems (FloatingItems-1.12.2-0.1.0.jar)
  
RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  com.therandomlabs.randompatches.core.RPTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
FutureMC (future-mc-0.2.11.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-13.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Sarous'/137976, l='Aurora', x=939.79, y=64.00, z=1711.19]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6286
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4
</details>

**Comment by MineDragonCZ** [comment]
...github autoclose...

**Comment by VirgilCore** [comment]
Just had this exact issue on my server.
[crash-2023-03-22_20.19.39-server.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11044521/crash-2023-03-22_20.19.39-server.txt)

Same sorta thing, InVaLiD (a player)

**Comment by VirgilCore** [comment]
It has happened again, in a different area. 

[crash-2023-03-23_02.35.50-server.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11046404/crash-2023-03-23_02.35.50-server.txt)

**Comment by VirgilCore** [comment]
I only just noticed that it seems to be bugging out when it tries to give the transport rings a default config and address.
