### ISSUE TITLE
Bug: Crash while dialing Uni Gate in End City

### ISSUE THREAD

**Issue by DeathToCountry** [Tau-ri-Dev/JSGMod-1.12.2#238]
**Describe the bug**
Ticking Block Entity from Uni Gate in End City while attempting to dial Uni Gate in End

**To Reproduce**
1. Change Uni Gate Config to support all three Capacitors, change config for 9 chevron to 7 chevron address
2. Build Uni gate in End, Full capacitors, address save in Dialer
3. Build Uni gate in first End Dimension after defeating Dragon, address save in dialer
4. Dial the Uni gate that exists where Dragon resides

**Expected behavior**
Successful Dialing of Uni Gate(after changing config to support Capacitors) to Uni gate where the Ender Dragon resides

**Mod version**
V. jsg-1.12.2-4.11.0.5-client

**Additional context**
Crash Report:

Description: Ticking block entity

java.lang.ClassCastException: tauri.dev.jsg.stargate.network.SymbolMilkyWayEnum cannot be cast to tauri.dev.jsg.stargate.network.SymbolUniverseEnum
	at tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile.activateSymbolServer(StargateUniverseBaseTile.java:341)
	at tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile.addSymbolToAddress(StargateUniverseBaseTile.java:346)
	at tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile.executeTask(StargateUniverseBaseTile.java:413)
	at tauri.dev.jsg.tileentity.util.ScheduledTask.update(ScheduledTask.java:159)
	at tauri.dev.jsg.tileentity.util.ScheduledTask.iterate(ScheduledTask.java:245)
	at tauri.dev.jsg.tileentity.stargate.StargateAbstractBaseTile.func_73660_a(StargateAbstractBaseTile.java:906)
	at tauri.dev.jsg.tileentity.stargate.StargateClassicBaseTile.func_73660_a(StargateClassicBaseTile.java:922)
	at tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile.func_73660_a(StargateUniverseBaseTile.java:118)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

Detailed Walkthrough:

Stacktrace:
	at tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile.activateSymbolServer(StargateUniverseBaseTile.java:341)
	at tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile.addSymbolToAddress(StargateUniverseBaseTile.java:346)
	at tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile.executeTask(StargateUniverseBaseTile.java:413)
	at tauri.dev.jsg.tileentity.util.ScheduledTask.update(ScheduledTask.java:159)
	at tauri.dev.jsg.tileentity.util.ScheduledTask.iterate(ScheduledTask.java:245)
	at tauri.dev.jsg.tileentity.stargate.StargateAbstractBaseTile.func_73660_a(StargateAbstractBaseTile.java:906)
	at tauri.dev.jsg.tileentity.stargate.StargateClassicBaseTile.func_73660_a(StargateClassicBaseTile.java:922)
	at tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile.func_73660_a(StargateUniverseBaseTile.java:118)

-- Block entity being ticked --
Details:
	Name: jsg:stargate_universe_base_block // tauri.dev.jsg.tileentity.stargate.StargateUniverseBaseTile
	Block type: ID #884 (tile.jsg.stargate_universe_base_block // tauri.dev.jsg.block.stargate.StargateUniverseBaseBlock // jsg:stargate_universe_base_block)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-889,56,-630), Chunk: (at 7,3,10 in -56,-40; contains blocks -896,0,-640 to -881,255,-625), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Actual block type: ID #884 (tile.jsg.stargate_universe_base_block // tauri.dev.jsg.block.stargate.StargateUniverseBaseBlock // jsg:stargate_universe_base_block)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

***Addtl Info:
Mods and Libs Used:***

SpeedsterHeroes-1.12.2-2.2.1.jar
LucraftCore-1.12.2-2.4.16.jar
HeroesExpansion-1.12.2-1.3.5.jar
star-tech-1.1.1.jar
AvengersTech+4.3.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
CTM-MC1.12.2-1.0.2.31.jar
PTRLib-1.0.4.jar
Decocraft-2.6.3_1.12.2.jar
jei_1.12.2-4.16.1.302.jar
ElectroblobsWizardry-4.3.9.jar
industrialcraft-2-2.8.221-ex112.jar
OpenComputers-MC1.12.2-1.7.5.192.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
jsg-1.12.2-4.11.0.5-client.jar
Patchouli-1.0-23.6.jar
PymTech-1.12.2-1.0.2.jar
railcraft-12.0.0.jar
the-fifth-world-0.5.1.jar
WR-CBE-1.12.2-2.3.2.33-universal.jar

***Addons used:***
Ben_10_Addon_1.4.3(by Matterfall)
Danny+Phantom+Addon+1.0+Release(by Nexominer)

**Comment by DeathToCountry** [comment]
Issue MAY be caused by using Ancient zpm hub as power source
