### ISSUE TITLE
Bug: Null Pointer Exception in structure generation 

### ISSUE THREAD

**Issue by Jimbologo** [Tau-ri-Dev/JSGMod-1.12.2#247]
Stacktrace: 

```

java.lang.NullPointerException: Ticking block entity
	at tauri.dev.jsg.stargate.network.StargatePos.<init>(StargatePos.java:25)
	at tauri.dev.jsg.tileentity.stargate.StargateAbstractBaseTile.setGateAddress(StargateAbstractBaseTile.java:474)
	at tauri.dev.jsg.tileentity.stargate.StargateAbstractBaseTile.refresh(StargateAbstractBaseTile.java:483)
	at tauri.dev.jsg.block.stargate.StargateAbstractBaseBlock.func_176213_c(StargateAbstractBaseBlock.java:162)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.world.gen.structure.template.Template.func_189960_a(Template.java:242)
	at tauri.dev.jsg.worldgen.structures.JSGStructure.generateStructure(JSGStructure.java:139)
	at tauri.dev.jsg.worldgen.structures.JSGStructure.generateStructure(JSGStructure.java:116)
	at tauri.dev.jsg.worldgen.structures.JSGStructuresGenerator.generateStructure(JSGStructuresGenerator.java:105)
	at tauri.dev.jsg.worldgen.structures.JSGStructuresGenerator.generateStructure(JSGStructuresGenerator.java:48)
	at tauri.dev.jsg.worldgen.structures.JSGStructuresGenerator.generate(JSGStructuresGenerator.java:39)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at tauri.dev.jsg.util.LinkingHelper.findClosestUnlinked(LinkingHelper.java:35)
	at tauri.dev.jsg.tileentity.dialhomedevice.DHDMilkyWayTile.updateLinkStatus(DHDMilkyWayTile.java:81)
	at tauri.dev.jsg.tileentity.dialhomedevice.DHDAbstractTile.func_73660_a(DHDAbstractTile.java:279)
	at tauri.dev.jsg.tileentity.dialhomedevice.DHDMilkyWayTile.func_73660_a(DHDMilkyWayTile.java:55)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Fredyman95** [comment]
We need more information - complete crashlog file not just part of it

**Comment by Jimbologo** [comment]
Apologies for that, Here is the crashlog file.
[crash-2023-05-10_13.48.20-server.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11442942/crash-2023-05-10_13.48.20-server.txt)

**Comment by MineDragonCZ** [comment]
Can u provide some more info, please? I do not know when this happened and what was going on before this crash.

**Comment by Jimbologo** [comment]
Yeah so this is when loading a fresh new world up it crashes with this, I removed JSG and found that a stargate was trying to spawn in (i found stargate stone brick base) so i believe when loading the world it tries to generate a stargate but crashes when doing so

**Comment by Jimbologo** [comment]
> Can u provide some more info, please? I do not know when this happened and what was going on before this crash.

let us know if there is any other info you may need :)

**Comment by Jimbologo** [comment]
oh also, Latest version that does work is "jsg-1.12.2-4.10.1.1-client.jar" which I believe is before you did the rewrite of the mod, Any version of the mod past the first rewrite version fails with the same issue

**Comment by Jimbologo** [comment]
And also The place in which it was trying to generate the stargate ended up floating in the air on top of trees if that helps at all

**Comment by MineDragonCZ** [comment]
> oh also, Latest version that does work is "jsg-1.12.2-4.10.1.1-client.jar" which I believe is before you did the rewrite of the mod, Any version of the mod past the first rewrite version fails with the same issue

Thanks for info. So in newest version it's NOT happening?

**Comment by Jimbologo** [comment]
No, it is still not working on latest version sorry if i confused what I was saying just meant version 4.11 upwards it’s broken in including the latest version

**Comment by maximogta** [comment]
Same issue here

**Comment by maximogta** [comment]
[latest.log](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11502134/latest.log)
[crash-2023-05-17_18.40.02-client.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11502135/crash-2023-05-17_18.40.02-client.txt)
The crash logs

**Comment by MineDragonCZ** [comment]
> [latest.log](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11502134/latest.log)
> [crash-2023-05-17_18.40.02-client.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11502135/crash-2023-05-17_18.40.02-client.txt)
> The crash logs

Different thing... Probably corrupted textures or wrong usage of a module...

**Comment by MineDragonCZ** [comment]
> No, it is still not working on latest version sorry if i confused what I was saying just meant version 4.11 upwards it’s broken in including the latest version 

Strange
